Dynamic unrolling through time, with various step length

In [1]:
import tensorflow as tf
n_steps = 2
n_inputs = 3
n_neurons = 5
seq_length = tf.placeholder(tf.int32, [None])
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, 
                                    dtype=tf.float32, sequence_length=seq_length)
init = tf.global_variables_initializer()

In [4]:
import numpy as np
X_batch = np.array([
    [[0,1,2],[9,8,7]],
    [[3,4,5],[0,0,0]],
    [[6,7,8],[6,5,4]],
    [[9,0,1],[3,2,1]]
])
seq_length_batch = np.array([2,1,1,2])
with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], 
                                      feed_dict={X:X_batch, seq_length:seq_length_batch})

In [5]:
print(outputs_val)

[[[ 0.13011083  0.23979639  0.5886007   0.22626297 -0.8584525 ]
  [-0.04336056 -0.99999952 -0.82680064  0.79594553 -0.99999952]]

 [[ 0.28593659 -0.95863199  0.30299544  0.75100833 -0.99925208]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.42797774 -0.99945307 -0.04985154  0.93789667 -0.9999963 ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.63311613 -0.99972266 -0.97645068  0.98610139 -0.67764986]
  [ 0.40891263 -0.89833218 -0.9665913  -0.43341005 -0.86358535]]]
