RNN using TensorFlow API

In [1]:
import tensorflow as tf
n_steps = 2
n_inputs = 3
n_neurons = 5
X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
X_seqs = tf.unstack(tf.transpose(X, perm=[1,0,2]))
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, X_seqs, dtype=tf.float32)
outputs = tf.transpose(tf.stack(output_seqs), perm=[1,0,2])
init = tf.global_variables_initializer()

In [2]:
import numpy as np

X_batch = np.array([
    [[0,1,2],[9,8,7]],
    [[3,4,5],[0,0,0]],
    [[6,7,8],[6,5,4]],
    [[9,0,1],[3,2,1]]
])
with tf.Session() as sess:
    init.run()
    outputs_val = sess.run(outputs, feed_dict={X: X_batch})

In [3]:
print(outputs_val)

[[[-0.65793943  0.85134804  0.89435643 -0.96045494  0.56979966]
  [-0.88419211  0.99994397  0.99999964 -0.99999994  0.97433251]]

 [[-0.82770199  0.99841243  0.99958348 -0.99996138  0.92479438]
  [-0.87660336 -0.52617532  0.66227442 -0.36289352 -0.21328598]]

 [[-0.91740936  0.99998432  0.99999851 -0.99999994  0.98892057]
  [-0.89381266  0.9915691   0.99989337 -0.99995953  0.80158693]]

 [[ 0.87710726  0.58275068  0.38136196  0.56551045 -0.19822693]
  [ 0.53357482  0.94894201  0.91977066 -0.5986799  -0.64714098]]]


In [4]:
from datetime import datetime
now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
logdir = "../tf_logs/run-{}/".format(now)
file_writer = tf.summary.FileWriter(logdir, graph=tf.get_default_graph())
file_writer.flush()