A simple hard-coded RNN

In [26]:
import tensorflow as tf

n_inputs = 3
n_neurons = 5
X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])
Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))
Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(X1, Wx) + tf.matmul(Y0, Wy) + b)
init = tf.global_variables_initializer()

In [27]:
import numpy as np

X0_batch = np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]])
X1_batch = np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]])
with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})

In [28]:
print(Y0_val)

[[-0.94016325  0.99722445 -0.16729888  0.98118621  0.24385518]
 [-0.99997658  1.         -0.99643111  0.99998802  0.99998993]
 [-1.          1.         -0.99999124  1.          1.        ]
 [-0.99999976  1.         -1.          0.17348607  1.        ]]


In [29]:
print(Y1_val)

[[-1.          1.         -1.          0.99999988  1.        ]
 [ 0.15655734 -0.22916323  0.82082105 -0.74780488  0.98301315]
 [-0.99998713  1.         -0.99981785  0.99942386  1.        ]
 [-0.9843955   0.99998868 -0.80231541  0.65045738  0.99999893]]
